spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/webdb"
    username: "root"
    password: "Qortmdcks95"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

com:
  example:
    upload:
      path: upload

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace



server:
  servlet:
    session:
      timeout: 90m


